// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

package server

import (
	"context"

	"bookstore/rpc/transform/example.com/project/protos/fizz"
	"bookstore/rpc/transform/internal/logic"
	"bookstore/rpc/transform/internal/svc"
)

type TransformerServer struct {
	svcCtx *svc.ServiceContext
}

func NewTransformerServer(svcCtx *svc.ServiceContext) *TransformerServer {
	return &TransformerServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformerServer) Expand(ctx context.Context, in *fizz.ExpandReq) (*fizz.ExpandResp, error) {
	l := logic.NewExpandLogic(ctx, s.svcCtx)
	return l.Expand(in)
}

func (s *TransformerServer) Shorten(ctx context.Context, in *fizz.ShortenReq) (*fizz.ShortenResp, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}
